name: Remote Tunnel via ngrok

on:
  workflow_dispatch: # Allow manual trigger
  push:
    branches:
      - main  # Runs on push to the main branch

jobs:
  tunnel:
    runs-on: ubuntu-22.04  # Use a stable and supported version
    steps:
      - name: Download and Install ngrok
        run: |
          # Download ngrok binary
          curl -Lo ngrok.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip
          unzip ngrok.zip
          sudo mv ngrok /usr/local/bin/
      
      - name: Start SSH Tunnel
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          # Authenticate ngrok with your token
          ngrok config add-authtoken $NGROK_AUTH_TOKEN
          # Start ngrok tunnel
          nohup ngrok tcp 22 > ngrok.log &
          sleep 5
          # Retrieve the tunnel URL
          NGROK_URL=$(curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "Tunnel established at: $NGROK_URL"
          echo "::set-output name=ngrok_url::$NGROK_URL"
