name: Remote Tunnel via ngrok

on:
  workflow_dispatch: # Allow manual trigger
  push:
    branches:
      - main  # Runs on push to the main branch

jobs:
  tunnel:
    runs-on: ubuntu-22.04  # Use a stable and supported version
    steps:
      - name: Set up ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc > /dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com stable main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok

      - name: Start SSH Tunnel
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          echo "authtoken: $NGROK_AUTH_TOKEN" > ~/.ngrok.yml
          nohup ngrok tcp 22 > ngrok.log &
          sleep 5
          NGROK_URL=$(curl -s http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url')
          echo "Tunnel established at: $NGROK_URL"
          echo "::set-output name=ngrok_url::$NGROK_URL"
